baseURL = 'https://gr8stalin.github.io/fighting-game-notes/'
locale = 'en-us'
title = 'Fighting Game Notes by Gr8Stalin'

[module]
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false

[markup.goldmark.renderer]
    unsafe = true

[[menu.primary]]
    name  = "Docs"
    url = "/docs/"
    identifier = "docs"
    weight = 10

[params]

    [params.footer]
        copyright = "Built with GitHub Pages and [**Lotus Docs**](https://github.com/colinwilson/lotusdocs)"
    
    [params.social]
        github = "gr8stalin/fighting-game-notes"
        twitter = "MustacheStalin"

    [params.docs]
        title = "Fighting Game Notes"
        darkMode = true
        repoUrl = "https://github.com/gr8stalin/fighting-game-notes"